learning_log/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url

from . import views
urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Show about the website
    url(r'about', views.about, name='about'),
    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),
    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
    name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from . import views



urlpatterns = [
    # Login page
    url(r'^login/$', LoginView.as_view(),{'registration/login.html': 'users/login.html'}, name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/$', views.register, name='register'), 
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, )
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    text = models.TextField()
    photo_add = models.ImageField(null=True, blank= True, upload_to ="images/")
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

        

    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'photo_add']
        labels = {'text': '', 'photo_add':'',}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# LIST OF VIEWS
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

def about(request):
    """About the student"""
    return render(request, 'learning_logs/about.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/base.html" %}

{% block content %}
		<div id="header">
			<h1 class="hover"><p style="font-family:verdana"> <p style="font-size:50px">Information about myself</p></h1>
			<p id="name"><p style="font-family:verdana"> <p style="font-size:30px">Jerou Jeuell U. Espelita</p>
			<a href="mailto:1820158@ub.edu.ph><p id="email">1820158@ub.edu.ph</p></a>
			<p>or</p>
			<a href="mailto:jeroujeuell312@gmail.com><p id="email">jeroujeuell312@gmail.com</p></a>

		</div>
		<h2><p style="font-family:verdana"> <p style="font-size:50px">Myself</p></h2>
			<img src="https://live.staticflickr.com/65535/52160536507_45e63904ca_s.jpg">
		<h2><p style="font-size:50px">About Me</p></h2>
			<p style="font-family:verdana"> <p style="font-size:30px">My name is Jerou Jeuell Espelita. I have lived in both Brgy Kayumanggi and Brgy 1 in Lipa City.
			Some of my favorite things to do are read, 
			listen to music, and ride bicycle.
			These are activities that I enjoy immensely and indulge in daily.
			I look up mostly to my family members, especially
			my mom, as a guiding figure in life. I also love watching movies and animes.</p>
			<h2>Favorite Movies</h2>
			<ul>
				<li><p style="font-family:verdana"> <p style="font-size:30px">Inception</p></li>
				<p><p style="font-family:verdana"> <p style="font-size:30px">Interstellar</p></li>
				<li><p style="font-family:verdana"> <p style="font-size:30px">Ready Player One</p></li>
				<li><p style="font-family:verdana"> <p style="font-size:30px">Inside out</p></li>
				<li><p style="font-family:verdana"> <p style="font-size:30px">Prisoners</p></li>
			</ul>
			<h2><p style="font-family:verdana"> <p style="font-size:50px">Favorite Anime</h2>
			<table border="1"> 
				<tr>
					<td><p style="font-family:verdana"> <p style="font-size:30px">One Piece </p></td>
					<td><p style="font-family:verdana"> <p style="font-size:30px">Attack on Titan</p></td>
					
				</tr>
				<tr>
					<td><p style="font-family:verdana"> <p style="font-size:30px">My Hero Academia</p></td>
					<td><p style="font-family:verdana"> <p style="font-size:30px">Black Clover</p></td>
				</tr>
				<tr>
					<td><p style="font-family:verdana"> <p style="font-size:30px">Bungou Straydogs</p></p></td>
					<td><p style="font-family:verdana"> <p style="font-size:30px">Vinland Saga</p></td>
				<tr>
			</table>
		<p>Purok 4, Brgy Kayumanggi<p>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home Page</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
       
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            </button>
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Home Page</a>
        </div>
       
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">Exercises</a></li>
            </ul>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:about' %}">About the Student</a></li>
            </ul>
       
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">log out</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}">register</a></li>
                    <li><a href="{% url 'users:login' %}">log in</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
       
        </div>
        </nav>
        <div class="container">
            <div class="page-header">
           {% block header %}{% endblock header %}
            </div>
            <div>
            {% block content %}{% endblock content %}
            </div>
        </div> <!-- /container -->

        <style>
            body {
              height: 100vh;
              background-image: url(https://mcdn.wallpapersafari.com/medium/82/84/zkM4FJ.png);
              background-size: cover;
              background-repeat: no-repeat;
              background-attachment: fixed;
              width: 100%;
          }

        </style>


    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class='jumbotron'>
        <h1>Object Oriented Programming</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <img src="https://live.staticflickr.com/65535/52161606716_7c16e037c7_s.jpg" widht= 200 height =200>
    </h2>
    <h2>
        Object Oriented programming (OOP) is a programming paradigm that relies on the concept of classes and objects. 
        It is used to structure a software program into simple, reusable pieces of code blueprints (usually called classes), which are used to create individual instances of objects
    </h2>
    <h2>
        OOP focuses on the objects that developers want to manipulate rather than the logic required 
        to manipulate them. This approach to programming is well-suited for programs that are large, 
        complex and actively updated or maintained. This includes programs for manufacturing and design, 
        as well as mobile applications; for example, OOP can be used for manufacturing system simulation 
        software.
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <button name ='submit'>add entry</button>
    </form>
    <div>
        {% if new_entry.photo_add %}
        <img src="{{ new_entry.photo_add.url }}"> 
        {% endif %}
    </div>



{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method='post'
        class="form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                            edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
            <div>
                {% if entry.photo_add %}
                <img src="{{ entry.photo_add.url }}" width="1150" length="1150"> 
                {% endif %}
            </div>
            
        </div> <!-- panel -->

    {% empty %}
            There are no entries for this topic yet.
    {% endfor %}

{% endblock content %}
       

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Exercises</h1>
{% endblock header %}

{% block content %}


    <ul>
        {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>

{% endblock content %}